#!/bin/bash
./tests/echo-reply-default.sh $1 ${@:2} localhost
./tests/destination-unreachable-destination-net-unreachable.sh $1 ${@:2} localhost
./tests/destination-unreachable-destination-host-unreachable.sh $1 ${@:2} localhost
./tests/destination-unreachable-destination-protocol-unreachable.sh $1 ${@:2} localhost
./tests/destination-unreachable-destination-port-unreachable.sh $1 ${@:2} localhost
./tests/destination-unreachable-fragmentation-needed-and-df-set.sh $1 ${@:2} localhost
./tests/destination-unreachable-source-route-failed.sh $1 ${@:2} localhost
./tests/destination-unreachable-network-unknown.sh $1 ${@:2} localhost
./tests/destination-unreachable-host-unknown.sh $1 ${@:2} localhost
./tests/destination-unreachable-host-isolated.sh $1 ${@:2} localhost
./tests/destination-unreachable-net-ano.sh $1 ${@:2} localhost
./tests/destination-unreachable-host-ano.sh $1 ${@:2} localhost
./tests/destination-unreachable-destination-network-unreachable-at-this-tos.sh $1 ${@:2} localhost
./tests/destination-unreachable-destination-host-unreachable-at-this-tos.sh $1 ${@:2} localhost
./tests/destination-unreachable-pkt-filtered.sh $1 ${@:2} localhost
./tests/destination-unreachable-precedence-violation.sh $1 ${@:2} localhost
./tests/destination-unreachable-precedence-cutoff.sh $1 ${@:2} localhost
./tests/destination-unreachable-destination-host-unreachable-at-this-tos.sh $1 ${@:2} localhost
./tests/source-quench-default.sh $1 ${@:2} localhost
./tests/redirect-redirect-network.sh $1 ${@:2} localhost
./tests/redirect-redirect-host.sh $1 ${@:2} localhost
./tests/redirect-redirect-type-of-service-and-network.sh $1 ${@:2} localhost
./tests/redirect-redirect-type-of-service-and-host.sh $1 ${@:2} localhost
./tests/echo-request-default.sh $1 ${@:2} localhost
./tests/time-exceeded-time-to-live-exceeded.sh $1 ${@:2} localhost
./tests/time-exceeded-frag-reassembly-time-exceeded.sh $1 ${@:2} localhost
./tests/timestamp-default.sh $1 ${@:2} localhost
./tests/timestamp-reply-default.sh $1 ${@:2} localhost
./tests/info-request-default.sh $1 ${@:2} localhost
./tests/info-reply-default.sh $1 ${@:2} localhost
./tests/address-request-default.sh $1 ${@:2} localhost
./tests/address-mask-reply-default.sh $1 ${@:2} localhost
